### ISSUE TITLE
Challenger == Applicant ?

### ISSUE THREAD

**Issue by bingen** [aragonlabs/curation#14]
Should we allow applicants to challenge their own applications? What should be the outcome?

**Comment by izqui** [comment]
I don't see why not. It wouldn't be super smart as they could potentially lose part of their deposit when it is dispensed to other voters in the challenge. 

Given that there is no identity layer to limit who can submit applications or start a challenge, an individual can do this regardless by using multiple accounts.

**Comment by bingen** [comment]
Yes, I agree. It was actually kind of a note to myself, to review the code and check that there was no issue here (like an `if...else` clause that should be not exclusive, or something like that). I didn't see anything like that, so closing it. The [`moveTokens`](https://github.com/aragon/aragon-apps/blob/b968e3ec9ab70cf6cfbfa5ebca8a58460669e7d1/future-apps/staking/contracts/Staking.sol#L208) part would the most stupid, haha, but no big deal I guess.
Thanks!
